const {
  TRAVEL_START_AIRWAY_PASSWORD,
  TRAVEL_START_AIRWAY_USERNAME,
  TRAVEL_START_SA_PASSWORD,
  TRAVEL_START_SA_USERNAME,
  TRAVEL_START_AE_USERNAME,
  TRAVEL_START_AE_PASSWORD,
  TRAVEL_START_KW_USERNAME,
  TRAVEL_START_KW_PASSWORD
} = process.env;

const pos = {
  EG: {
    user_name: TRAVEL_START_AIRWAY_USERNAME,
    password: TRAVEL_START_AIRWAY_PASSWORD
  },
  SA: {
    user_name: TRAVEL_START_SA_USERNAME,
    password: TRAVEL_START_SA_PASSWORD
  },
  AE: {
    user_name: TRAVEL_START_AE_USERNAME,
    password: TRAVEL_START_AE_PASSWORD
  },
  KW: {
    user_name: TRAVEL_START_KW_USERNAME,
    password: TRAVEL_START_KW_PASSWORD
  }
};

export default pos;
